on: [push, pull_request]
name: rustls

jobs:
  build:
    name: Build+test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # test a bunch of toolchains on ubuntu
        rust:
          - stable
          - beta
          - nightly
          - 1.47.0 # our MSRV
        os: [ubuntu-18.04]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install ${{ matrix.rust }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: cargo build (debug; default features)
        run: cargo build

      - name: cargo test (debug; default features)
        run: cargo test
        env:
          RUST_BACKTRACE: 1

      - name: cargo test (debug; all features)
        run: cargo test --all-features
        env:
          RUST_BACKTRACE: 1

      - name: cargo build (debug; no default features)
        run: cargo build --no-default-features
        working-directory: rustls

      - name: cargo test (debug; no default features; no run)
        run: cargo test --no-default-features --no-run
        working-directory: rustls

      - name: cargo test (release; no run)
        run: cargo test --release --no-run


  bogo:
    name: BoGo test suite
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install golang toolchain
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: Run test suite
        working-directory: bogo
        run: ./runme


